version: "3.9"

networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true   

services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal   

  app:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8000:8000"   
      depends_on:
        - mysql
      networks:
        - internal   
        - public     

volumes:
  mysql_data:
    driver: local